namespace Emdep.Geos.Services.Core.Models
{
    public class LogEntriesByActionPlan { }
    public class ActionPlanComment { }
    public class AttachmentsByTask { }
    public class Currency { }
    public class SalesStatusType { }
    public class TemplateTag { }
    public class CountryGroup { }
    public class JobDescription { }
    public class CompanyShift { }
    public class EmployeeContact { }
    public class EmployeeDocument { }
    public class EmployeeLanguage { }
    public class EmployeeEducationQualification { }
    public class EmployeeContractSituation { }
    public class EmployeeFamilyMember { }
    public class EmployeeJobDescription { }
    public class EmployeeChangelog { }
    public class EmployeeProfessionalEducation { }
    public class EmployeePolyvalence { }
    public class ContractSituation { }
    public class EmployeeAnnualLeave { }
    public class EmployeeShift { }
    public class EmployeeLeave { }
    public class EmployeeExitEvent { }
    public class EmployeeAnnualAdditionalLeave { }
    public class EmployeeEquipmentAndTools { }
    public class ShippingAddress { }
    public class CompanySchedule { }
    public class CompanyAnnualSchedule { }
    public class CompanySetting { }
    public class CompanyChangelog { }
    public class Offer { }
    public class Supplier { }
    public class GeosProvider { }
    public class SiteUserPermission { }
    public class User { }
    public class EnterpriseGroup { }
    public class LogEntryBySite { }
    public class SalesTargetBySite { }
    public class SitesByBusinessProduct { }
    public class CustomerSort { }
    public class PeopleType { }
    public class LogEntriesByContact { }
    public class Competitor { }
    public class SitesWithCustomer { }

}
